-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 22:52:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 4e
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 4e
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4e` ;
USE `4e` ;

-- -----------------------------------------------------
-- Table `4e`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`usuario` (
  `correo` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4e`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`proyecto` (
  `idproyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario_correo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idproyecto`),
  INDEX `fk_proyecto_usuario1_idx` (`usuario_correo` ASC),
  CONSTRAINT `fk_proyecto_usuario1`
    FOREIGN KEY (`usuario_correo`)
    REFERENCES `4e`.`usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4e`.`stakeholder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`stakeholder` (
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `proyecto_idproyecto` INT NOT NULL,
  `idStakeholder` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_stakeholder_proyecto1_idx` (`proyecto_idproyecto` ASC),
  PRIMARY KEY (`idStakeholder`),
  CONSTRAINT `fk_stakeholder_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `4e`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4e`.`goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`goal` (
  `nombre` VARCHAR(40) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `stakeholder_idStakeholder` INT NOT NULL,
  `idGoal` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idGoal`),
  INDEX `fk_goal_stakeholder1_idx` (`stakeholder_idStakeholder` ASC),
  CONSTRAINT `fk_goal_stakeholder1`
    FOREIGN KEY (`stakeholder_idStakeholder`)
    REFERENCES `4e`.`stakeholder` (`idStakeholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4e`.`subgoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`subgoal` (
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `idsubgoal` INT NOT NULL AUTO_INCREMENT,
  `goal_idGoal` INT NOT NULL,
  PRIMARY KEY (`idsubgoal`),
  INDEX `fk_subgoal_goal1_idx` (`goal_idGoal` ASC),
  CONSTRAINT `fk_subgoal_goal1`
    FOREIGN KEY (`goal_idGoal`)
    REFERENCES `4e`.`goal` (`idGoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4e`.`categorianfr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`categorianfr` (
  `idcategorianfr` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorianfr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4e`.`nfr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`nfr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `categorianfr_idcategorianfr` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nfr_categorianfr1_idx` (`categorianfr_idcategorianfr` ASC),
  CONSTRAINT `fk_nfr_categorianfr1`
    FOREIGN KEY (`categorianfr_idcategorianfr`)
    REFERENCES `4e`.`categorianfr` (`idcategorianfr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4e`.`listadonfr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4e`.`listadonfr` (
  `nfr_id` INT NOT NULL,
  `subgoal_idsubgoal` INT NOT NULL,
  PRIMARY KEY (`nfr_id`, `subgoal_idsubgoal`),
  INDEX `fk_nfr_has_subgoal_subgoal1_idx` (`subgoal_idsubgoal` ASC),
  INDEX `fk_nfr_has_subgoal_nfr1_idx` (`nfr_id` ASC),
  CONSTRAINT `fk_nfr_has_subgoal_nfr1`
    FOREIGN KEY (`nfr_id`)
    REFERENCES `4e`.`nfr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nfr_has_subgoal_subgoal1`
    FOREIGN KEY (`subgoal_idsubgoal`)
    REFERENCES `4e`.`subgoal` (`idsubgoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
